// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_analyze from "./routes/api/analyze.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_refresh from "./routes/api/auth/refresh.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_foods_id_ from "./routes/api/foods/[id].ts";
import * as $api_foods_index from "./routes/api/foods/index.ts";
import * as $api_foods_upc_code_ from "./routes/api/foods/upc/[code].ts";
import * as $api_log_id_ from "./routes/api/log/[id].ts";
import * as $api_log_daily from "./routes/api/log/daily.ts";
import * as $api_log_index from "./routes/api/log/index.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $foods_id_ from "./routes/foods/[id].tsx";
import * as $foods_index from "./routes/foods/index.tsx";
import * as $foods_new from "./routes/foods/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $log_date_ from "./routes/log/[date].tsx";
import * as $log_index from "./routes/log/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $register from "./routes/register.tsx";
import * as $scan from "./routes/scan.tsx";
import * as $CameraCapture from "./islands/CameraCapture.tsx";
import * as $DailyLogManager from "./islands/DailyLogManager.tsx";
import * as $FoodLogForm from "./islands/FoodLogForm.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/analyze.ts": $api_analyze,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/refresh.ts": $api_auth_refresh,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/foods/[id].ts": $api_foods_id_,
    "./routes/api/foods/index.ts": $api_foods_index,
    "./routes/api/foods/upc/[code].ts": $api_foods_upc_code_,
    "./routes/api/log/[id].ts": $api_log_id_,
    "./routes/api/log/daily.ts": $api_log_daily,
    "./routes/api/log/index.ts": $api_log_index,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/foods/[id].tsx": $foods_id_,
    "./routes/foods/index.tsx": $foods_index,
    "./routes/foods/new.tsx": $foods_new,
    "./routes/index.tsx": $index,
    "./routes/log/[date].tsx": $log_date_,
    "./routes/log/index.tsx": $log_index,
    "./routes/login.tsx": $login,
    "./routes/register.tsx": $register,
    "./routes/scan.tsx": $scan,
  },
  islands: {
    "./islands/CameraCapture.tsx": $CameraCapture,
    "./islands/DailyLogManager.tsx": $DailyLogManager,
    "./islands/FoodLogForm.tsx": $FoodLogForm,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/RegisterForm.tsx": $RegisterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
